### ISSUE TITLE
你好，请问怎么修改字体？

### ISSUE THREAD

**Issue by cjliux** [wannaxiao/vuepress-theme-resume#14]
你好，请问怎么修改字体？

**Comment by komomoo** [comment]
1，修改浏览器默认字体。
2，开发者工具中，修改css。
3，修改源码。

**Comment by cjliux** [comment]
请问修改源码是在哪修改呢？
是index.styl里面body.font-family么？
我改了之后，页面还是显示宋体。浏览器我用的chrome。
