### ISSUE TITLE
如何将侧边栏隐藏？

### ISSUE THREAD

**Issue by zwx-zwx** [wannaxiao/vuepress-theme-resume#17]
如题

**Comment by lzzmm** [comment]
可以尝试放大到侧边栏自动隐藏再打印。

**Comment by Fostereee** [comment]
同问，目前我是用firefox的f12菜单手动删掉的侧边栏

**Comment by Fostereee** [comment]
我试了下在example/.vuepress/config.js里把themeConfig里的sidebar注释掉似乎就好了

**Comment by komomoo** [comment]
直接右键“打印”就行了，侧边栏不会进去的
