### ISSUE TITLE
考虑过将 vuepress 升级到 1.x 嘛？

### ISSUE THREAD

**Issue by yiliang114** [wannaxiao/vuepress-theme-resume#6]
因为有一些 api 有出入了，并且我遇到一些场景 0.x 不能满足，例如 base 指定 cdn 的前缀。 所以我更希望使用 1.x 的 vuepress . 本来刚刚提交了一个 pr , 先关掉了，先问问作者哈，有没有意向升级一下，可以的话 我提个 pr

**Comment by komomoo** [comment]
可以，你提吧～
